name: Publish JSR package

on:
  release:
    types: [published]

jobs:
  publish-jsr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint package
        run: |
          npx jsr publish --dry-run

      - name: Set version
        run: |
          cat jsr.json | jq '.version = "${{ github.event.release.tag_name }}"' | tee jsr.json

      - name: Publish package
        run: |
          npx jsr publish --allow-dirty
