name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install

      - name: Code style check
        run: |
          npm run fmt -- --check

      - name: Type check
        run: |
          npm run check

      - name: Unit tests
        run: |
          npm run test
