name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Unit tests
        run: |
          deno test

      - name: Lint source code
        run: |
          deno task lint

      - name: Lint by JSR
        run: |
          deno publish --dry-run
